### ISSUE TITLE
请问定时抢购是多线程还是单线程

### ISSUE THREAD

**Issue by zy19941113** [pujie1216/CSharp-Unifri#1]
10点场勾选5个商品，勾选定时抢购，软件逻辑是5个商品一起抢购，还是抢到一个抢下一个

**Comment by pujie1216** [comment]
肯定是一个一个啊，但是只抢文本框里返回已选择的商品，也就是不论勾选多少个，都只抢一个，联通限制了只有一个未支付订单，不论多线程还是同时抢购，和单线程没啥区别，而且间隔时间缩短跟多线程效果差不多的

**Comment by zy19941113** [comment]
联通没有限制只有一个未支付订单，意味着可以抢多个的。因为我今天抢购的时候，定时抢购加手动抢到两个

**Comment by zy19941113** [comment]
> 肯定是一个一个啊，但是只抢文本框里返回已选择的商品，也就是不论勾选多少个，都只抢一个，联通限制了只有一个未支付订单，不论多线程还是同时抢购，和单线程没啥区别，而且间隔时间缩短跟多线程效果差不多的
